#!/bin/bash

### Install Google Chrome ###
echo "Downloading Google Chrome..."
wget -nv -N -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb
