#!/bin/bash

### Clone the Git Dotfile Repository ###
echo ".cfg" ?? $HOME/.gitignore
git clone --bare git@github.com:ChevySSinSD/t430-debian-sway.git $HOME/.cfg
git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
git --git-dir=$HOME/.cfg/ --work-tree=$HOME fetch
git --git-dir=$HOME/.cfg/ --work-tree=$HOME reset --hard

### Install Dotfile Dependencies ###
# Install RobotoMono Hack Font
sudo apt install unzip
wget -nv -N -P ~/Downloads https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/RobotoMono.zip
unzip -qj ~/Downloads/RobotoMono.zip -d ~/.local/share/fonts/
fc-cache -f -v
