#!/bin/bash

### Install SwayWM and tools ###
sudo apt update -qq && sudo apt upgrade && sudo apt autoremove
sudo apt install sway swayidle waybar wofi light pulseaudio pamix playerctl tlp tlp-rdw acpi-call-dkms smartmontools

### Install Swaylock from source ###
# As of May 2022, Swaylock version 1.5 is the most recent version that will install on Debian Stable (Bullseye)
# Meson backports required to build Swaylock 1.5 from source in Debian Stable (Bullseye)
sudo apt install meson/bullseye-backports fish libgdk-pixbuf-2.0-dev cmake pkg-config libwayland-dev wayland-protocols libxkbcommon-dev libcairo2-dev
wget -nv -N -P ~/Downloads https://github.com/swaywm/swaylock/archive/refs/tags/1.5.tar.gz
(cd ~/Downloads; tar -xf 1.5.tar.gz; cd swaylock-1.5; meson build; ninja -C build; sudo ninja -C build install; sudo chmod a+s /usr/local/bin/swaylock)
sudo chmod a+s /usr/local/bin/swaylock

sudo reboot
