#!/bin/bash

### Install Sway and tools ###
sudo apt install sway swaybg swayidle waybar wofi

### Install Google Chrome ###
wget -N -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb

### Install Audio Controls
sudo apt install pulseaudio pamix

### Install Power Management
sudo apt install tlp tlp-rdw acpi-call-dkms
