#!/bin/bash

### Update and upgrade apt ###
sudo apt update && sudo apt upgrade

### Make Directories ###
mkdir -p ~/.local/share/fonts/
mkdir -p ~/.themes

### Install Sway and tools ###
sudo apt install sway swaybg swayidle waybar wofi

### Install Swaylock from source ###
sudo apt install meson/bullseye-backports fish libgdk-pixbuf-2.0-dev cmake pkg-config libwayland-dev wayland-protocols libxkbcommon-dev libcairo2-dev
wget -nv -N -P ~/Downloads https://github.com/mortie/swaylock-effects/archive/refs/tags/v1.6-3.tar.gz
(cd ~/Downloads; tar -xf v1.6-3.tar.gz; cd swaylock-effects-1.6-3; meson build; ninja -C build; sudo ninja -C build install; sudo chmod a+s /usr/local/bin/swaylock)

### Install Light (Backlight Control)
sudo apt install light

### Install Google Chrome ###
wget -nv -N -P ~/Downloads https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ~/Downloads/google-chrome-stable_current_amd64.deb

### Install Audio Controls ###
sudo apt install pulseaudio pamix

### Install Power Management ###
sudo apt install tlp tlp-rdw acpi-call-dkms smartmontools

### Install Media Player Control Daemon ###
sudo apt install playerctl

### Install RobotoMono Hack Font ###
sudo apt install unzip
wget -nv -N -P ~/Downloads https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/RobotoMono.zip
unzip -qj ~/Downloads/RobotoMono.zip -d ~/.local/share/fonts/
fc-cache -f -v

### Install Dracula GTK Theme ###
sudo apt install libglib2.0-bin
wget -nv -N -P ~/Downloads https://github.com/dracula/gtk/releases/latest/download/Dracula.tar.xz

### Install Printer and Scanner ###

# Install brother scanner driver
wget -nv -N -P ~/Downloads https://download.brother.com/welcome/dlf105200/brscan4-0.4.11-1.amd64.deb
sudo apt install ~/Downloads/brscan4-0.4.11-1.amd64.deb
sudo brsaneconfig4 -a name=Scanner model=HLL2380DW ip=192.168.88.238 #Setup network scanner

# Install printer setup
sudo apt install cups

### Cleanup ###
sudo apt remove termit # Termit does not work, use foot instead
sudo apt autoremove
sudo reboot
