#!/bin/bash

# Update apt
sudo apt update

### Install Libreoffice Calc ###
sudo apt install libreoffice-core libreoffice-calc libreoffice-gtk3

# Install LibreOffice numbertext extension
wget -N -P ~/Downloads https://extensions.libreoffice.org/assets/downloads/z/numbertext-1-0-5.oxt
sudo /usr/lib/libreoffice/program/unopkg add ~/Downloads/numbertext-1-0-5.oxt --shared -s -f

# Install LibreOffice icon theme
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-libreoffice-theme/master/install-papirus-root.sh | sh

# Install Spotifyd
wget -N -P ~/Downloads https://github.com/Spotifyd/spotifyd/releases/latest/download/spotifyd-linux-full.tar.gz
tar -xf ~/Downloads/spotifyd-linux-full.tar.gz --directory ~/.local/bin

# Install Spotify TUI
wget -N -P ~/Downloads https://github.com/Rigellute/spotify-tui/releases/latest/download/spotify-tui-linux.tar.gz
tar -xf ~/Downloads/spotify-tui-linux.tar.gz --directory ~/.local/bin

# Install TUI Apps
sudo apt install neofetch btop ranger inkscape rclone

### Set GTK Theme ###
gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

### Set GTK Font ###
gsettings set org.gnome.desktop.interface font-name 'Roboto 13'
gsettings set org.gnome.desktop.interface monospace-font-name 'Roboto Mono 13'

### Install Papirus Icons ###
sudo apt install papirus-icon-theme
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'

# Clean Up
sudo apt remove /usr/share/applications/display-im6.q16.desktop
sudo apt remove w3m imagemagick
sudo apt upgrade && sudo apt autoremove
sudo reboot
